"use client";

import React, { useState } from "react";
import jsPDF from "jspdf";
import { PRDHistory, PRDStructuredContent } from "@/lib/api";
import { Download, FileText, Copy, Check, X } from "lucide-react";

interface PRDViewerProps {
  prd: PRDHistory;
  onClose?: () => void;
}

/**
 * PRDViewer Component.
 * Displays structured PRD blueprint with client-side Download Markdown & Download PDF export buttons.
 */
export default function PRDViewer({ prd, onClose }: PRDViewerProps) {
  const [copied, setCopied] = useState<boolean>(false);

  // Safely parse structured JSON content from backend
  let parsedContent: PRDStructuredContent | null = null;
  try {
    parsedContent = JSON.parse(prd.content);
  } catch {
    parsedContent = null;
  }

  // Generate clean Markdown string representation
  const generateMarkdownString = (): string => {
    if (!parsedContent) return prd.content;

    let md = `# ${parsedContent.title}\n\n`;
    md += `## System Architecture Overview\n${parsedContent.architecture_overview}\n\n`;

    md += `## Database Schema Definitions\n`;
    parsedContent.database_tables.forEach((table) => {
      md += `### Table: \`${table.table_name}\`\n${table.description}\n\n`;
      md += `| Column Name | Type | Constraints |\n`;
      md += `| :--- | :--- | :--- |\n`;
      table.columns.forEach((col) => {
        md += `| \`${col.name}\` | \`${col.type}\` | ${col.constraints} |\n`;
      });
      md += `\n`;
    });

    md += `## Backend API Routes\n`;
    md += `| Method | Path | Function Summary |\n`;
    md += `| :--- | :--- | :--- |\n`;
    parsedContent.api_routes.forEach((route) => {
      md += `| **${route.method}** | \`${route.path}\` | ${route.summary} |\n`;
    });
    md += `\n`;

    md += `## Mermaid Architecture Diagram\n\`\`\`mermaid\n${parsedContent.mermaid_diagram}\n\`\`\`\n`;
    return md;
  };

  // Client-Side Download Markdown File
  const handleDownloadMarkdown = () => {
    const markdownText = generateMarkdownString();
    const blob = new Blob([markdownText], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    const filename = `${prd.title.toLowerCase().replace(/[^a-z0-9]/g, "_")}_prd.md`;
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Client-Side Download PDF File via jsPDF
  const handleDownloadPDF = () => {
    if (!parsedContent) return;

    const doc = new jsPDF();
    let y = 20;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 14;

    const checkPageBreak = (neededHeight: number) => {
      if (y + neededHeight >= pageHeight - 15) {
        doc.addPage();
        y = 20;
      }
    };

    // Document Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(parsedContent.title, margin, y);
    y += 10;

    // Subheader
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`Generated by Blueprint Engine | ID: ${prd.id.substring(0, 8)}`, margin, y);
    doc.setTextColor(0);
    y += 12;

    // Architecture Overview Section
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("1. Architecture Overview", margin, y);
    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const archLines = doc.splitTextToSize(parsedContent.architecture_overview, 180);
    checkPageBreak(archLines.length * 5);
    doc.text(archLines, margin, y);
    y += archLines.length * 5 + 8;

    // Database Tables Section
    checkPageBreak(15);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("2. Database Schema", margin, y);
    y += 7;

    parsedContent.database_tables.forEach((tbl) => {
      checkPageBreak(20);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text(`Table: ${tbl.table_name}`, margin, y);
      y += 5;

      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.text(`Description: ${tbl.description}`, margin, y);
      y += 6;

      tbl.columns.forEach((col) => {
        checkPageBreak(5);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.text(`- ${col.name} (${col.type}): ${col.constraints}`, margin + 4, y);
        y += 4.5;
      });
      y += 4;
    });

    // API Routes Section
    checkPageBreak(15);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("3. API Routes", margin, y);
    y += 7;

    parsedContent.api_routes.forEach((rt) => {
      checkPageBreak(6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.text(`[${rt.method}] ${rt.path} - ${rt.summary}`, margin, y);
      y += 5;
    });

    // Save generated PDF file
    const filename = `${prd.title.toLowerCase().replace(/[^a-z0-9]/g, "_")}_blueprint.pdf`;
    doc.save(filename);
  };

  // Copy Markdown content to clipboard
  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownString());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 space-y-6 shadow-2xl">
      {/* Header Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-800 pb-4">
        <div>
          <h2 className="text-xl font-bold text-gray-100">{prd.title}</h2>
          <p className="text-xs text-gray-400 font-mono mt-0.5">
            Created: {new Date(prd.created_at).toLocaleDateString()}
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopyMarkdown}
            className="inline-flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-gray-800 text-gray-200 text-xs font-semibold hover:bg-gray-700 transition-colors border border-gray-700"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? "Copied" : "Copy MD"}</span>
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="inline-flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-gray-800 text-gray-200 text-xs font-semibold hover:bg-gray-700 transition-colors border border-gray-700"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download MD</span>
          </button>

          <button
            onClick={handleDownloadPDF}
            className="inline-flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-gray-100 text-gray-950 text-xs font-semibold hover:bg-gray-300 transition-colors shadow"
          >
            <FileText className="w-3.5 h-3.5" />
            <span>Download PDF</span>
          </button>

          {onClose && (
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg bg-gray-800 text-gray-400 hover:text-gray-100 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Structured Content Display */}
      {parsedContent ? (
        <div className="space-y-6 text-sm text-gray-300">
          {/* Architecture Overview */}
          <section className="space-y-2">
            <h3 className="text-sm font-semibold text-gray-100 uppercase tracking-wider text-xs font-mono text-gray-400">
              Architecture Overview
            </h3>
            <div className="bg-gray-950 p-4 rounded-lg border border-gray-800 leading-relaxed text-gray-300">
              {parsedContent.architecture_overview}
            </div>
          </section>

          {/* Database Tables */}
          <section className="space-y-3">
            <h3 className="text-sm font-semibold text-gray-100 uppercase tracking-wider text-xs font-mono text-gray-400">
              Database Schemas
            </h3>
            <div className="grid grid-cols-1 gap-4">
              {parsedContent.database_tables.map((table, idx) => (
                <div key={idx} className="bg-gray-950 p-4 rounded-lg border border-gray-800 space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="font-mono font-bold text-gray-100 text-xs bg-gray-900 px-2.5 py-1 rounded border border-gray-800">
                      {table.table_name}
                    </span>
                    <span className="text-xs text-gray-400">{table.description}</span>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-left text-xs border-collapse">
                      <thead>
                        <tr className="border-b border-gray-800 text-gray-400 font-mono">
                          <th className="py-1.5 px-2">Column</th>
                          <th className="py-1.5 px-2">Type</th>
                          <th className="py-1.5 px-2">Constraints</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-800/50">
                        {table.columns.map((col, cIdx) => (
                          <tr key={cIdx} className="text-gray-300">
                            <td className="py-1.5 px-2 font-mono text-gray-200">{col.name}</td>
                            <td className="py-1.5 px-2 font-mono text-gray-400">{col.type}</td>
                            <td className="py-1.5 px-2 text-gray-400">{col.constraints}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* API Routes */}
          <section className="space-y-3">
            <h3 className="text-sm font-semibold text-gray-100 uppercase tracking-wider text-xs font-mono text-gray-400">
              Backend API Routes
            </h3>
            <div className="bg-gray-950 rounded-lg border border-gray-800 overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-gray-800 text-gray-400 font-mono">
                    <th className="py-2 px-3">Method</th>
                    <th className="py-2 px-3">Path</th>
                    <th className="py-2 px-3">Summary</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-800/50">
                  {parsedContent.api_routes.map((route, rIdx) => (
                    <tr key={rIdx}>
                      <td className="py-2 px-3 font-mono font-bold text-gray-200">{route.method}</td>
                      <td className="py-2 px-3 font-mono text-gray-300">{route.path}</td>
                      <td className="py-2 px-3 text-gray-400">{route.summary}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* Mermaid Diagram */}
          <section className="space-y-2">
            <h3 className="text-sm font-semibold text-gray-100 uppercase tracking-wider text-xs font-mono text-gray-400">
              Mermaid Architecture Syntax
            </h3>
            <pre className="bg-gray-950 p-4 rounded-lg border border-gray-800 text-xs font-mono text-gray-300 overflow-x-auto">
              <code>{parsedContent.mermaid_diagram}</code>
            </pre>
          </section>
        </div>
      ) : (
        <pre className="bg-gray-950 p-4 rounded-lg border border-gray-800 text-xs font-mono text-gray-300 overflow-x-auto">
          {prd.content}
        </pre>
      )}
    </div>
  );
}
